"use client";

import { Shield, Lock, CheckCircle, Award, Users, Zap } from "lucide-react";

// =============================================================================
// TYPES
// =============================================================================
interface TrustBadge {
  icon: React.ComponentType<{ className?: string }>;
  label: { fr: string; en: string };
  description?: { fr: string; en: string };
}

interface TrustBadgesProps {
  variant?: "compact" | "full" | "inline";
  className?: string;
  showDescriptions?: boolean;
}

// =============================================================================
// TRUST BADGES DATA - E-E-A-T: Trust Signals
// =============================================================================
const trustBadges: TrustBadge[] = [
  {
    icon: Shield,
    label: { fr: "RGPD Compliant", en: "GDPR Compliant" },
    description: {
      fr: "Vos données sont protégées conformément au RGPD",
      en: "Your data is protected in compliance with GDPR",
    },
  },
  {
    icon: Lock,
    label: { fr: "Connexion sécurisée", en: "Secure connection" },
    description: {
      fr: "Chiffrement SSL/TLS sur toutes les communications",
      en: "SSL/TLS encryption on all communications",
    },
  },
  {
    icon: CheckCircle,
    label: { fr: "Données chiffrées", en: "Encrypted data" },
    description: {
      fr: "Vos informations sont chiffrées au repos et en transit",
      en: "Your information is encrypted at rest and in transit",
    },
  },
  {
    icon: Users,
    label: { fr: "15K+ utilisateurs", en: "15K+ users" },
    description: {
      fr: "Rejoignez une communauté de professionnels",
      en: "Join a community of professionals",
    },
  },
];

const socialProofBadges: TrustBadge[] = [
  {
    icon: Award,
    label: { fr: "4.9/5 satisfaction", en: "4.9/5 satisfaction" },
    description: {
      fr: "Note moyenne de nos utilisateurs",
      en: "Average rating from our users",
    },
  },
  {
    icon: Zap,
    label: { fr: "500K+ posts créés", en: "500K+ posts created" },
    description: {
      fr: "Posts générés par notre communauté",
      en: "Posts generated by our community",
    },
  },
];

// =============================================================================
// COMPONENTS
// =============================================================================

/**
 * Trust Badges - Display trust signals for E-E-A-T compliance
 */
export function TrustBadges({
  variant = "compact",
  className = "",
  showDescriptions = false,
}: TrustBadgesProps) {
  // App is French-only, using "fr" as default
  const t = "fr" as const;

  if (variant === "inline") {
    return (
      <div className={`flex flex-wrap items-center gap-4 ${className}`}>
        {trustBadges.slice(0, 3).map((badge, index) => {
          const Icon = badge.icon;
          return (
            <div
              key={index}
              className="flex items-center gap-1.5 text-gray-500 dark:text-gray-400"
            >
              <Icon className="w-4 h-4" />
              <span className="text-xs">{badge.label[t]}</span>
            </div>
          );
        })}
      </div>
    );
  }

  if (variant === "compact") {
    return (
      <div className={`flex flex-wrap items-center justify-center gap-6 ${className}`}>
        {trustBadges.map((badge, index) => {
          const Icon = badge.icon;
          return (
            <div
              key={index}
              className="flex items-center gap-2 text-gray-600 dark:text-gray-400"
            >
              <div className="w-8 h-8 rounded-lg bg-gray-100 dark:bg-white/5 flex items-center justify-center">
                <Icon className="w-4 h-4 text-green-600 dark:text-green-400" />
              </div>
              <span className="text-sm font-medium">{badge.label[t]}</span>
            </div>
          );
        })}
      </div>
    );
  }

  // Full variant
  return (
    <div className={`grid grid-cols-2 md:grid-cols-4 gap-4 ${className}`}>
      {trustBadges.map((badge, index) => {
        const Icon = badge.icon;
        return (
          <div
            key={index}
            className="bg-white dark:bg-white/5 rounded-xl p-4 border border-gray-200 dark:border-white/10 text-center"
          >
            <div className="w-12 h-12 mx-auto rounded-xl bg-green-100 dark:bg-green-900/30 flex items-center justify-center mb-3">
              <Icon className="w-6 h-6 text-green-600 dark:text-green-400" />
            </div>
            <p className="font-medium text-gray-900 dark:text-white text-sm">
              {badge.label[t]}
            </p>
            {showDescriptions && badge.description && (
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                {badge.description[t]}
              </p>
            )}
          </div>
        );
      })}
    </div>
  );
}

/**
 * Social Proof Section - Display user metrics
 */
export function SocialProofBadges({ className = "" }: { className?: string }) {
  // App is French-only, using "fr" as default
  const t = "fr" as const;

  return (
    <div className={`flex flex-wrap items-center justify-center gap-8 ${className}`}>
      {socialProofBadges.map((badge, index) => {
        const Icon = badge.icon;
        return (
          <div key={index} className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
              <Icon className="w-5 h-5 text-blue-600 dark:text-blue-400" />
            </div>
            <div>
              <p className="font-bold text-gray-900 dark:text-white">
                {badge.label[t]}
              </p>
              {badge.description && (
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {badge.description[t]}
                </p>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

/**
 * Trust Footer - Compact trust signals for footer
 */
export function TrustFooter({ className = "" }: { className?: string }) {
  return (
    <div className={`flex flex-wrap items-center justify-center gap-4 text-xs text-gray-500 dark:text-gray-400 ${className}`}>
      <div className="flex items-center gap-1">
        <Shield className="w-3.5 h-3.5" />
        <span>RGPD</span>
      </div>
      <span className="hidden sm:inline">•</span>
      <div className="flex items-center gap-1">
        <Lock className="w-3.5 h-3.5" />
        <span>SSL</span>
      </div>
      <span className="hidden sm:inline">•</span>
      <div className="flex items-center gap-1">
        <CheckCircle className="w-3.5 h-3.5" />
        <span>Données sécurisées</span>
      </div>
    </div>
  );
}

export default TrustBadges;
