import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Configuration pour Vercel (sans output: "export")
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**.googleusercontent.com",
      },
      {
        protocol: "https",
        hostname: "**.licdn.com",
      },
      {
        protocol: "https",
        hostname: "**.linkedin.com",
      },
      {
        protocol: "https",
        hostname: "**.cdninstagram.com",
      },
      {
        protocol: "https",
        hostname: "**.fbcdn.net",
      },
      {
        // Unsplash - Images libres de droits pour temoignages
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
    // Performance: optimize images for Core Web Vitals (LCP)
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200],
    imageSizes: [16, 32, 48, 64, 96, 128, 256],
    minimumCacheTTL: 60 * 60 * 24 * 365, // 1 year cache for images
    // Allow `?v=N` cache-busters on landing-page screenshot PNGs
    // (regenerated by `npm run generate-previews`).
    localPatterns: [
      { pathname: "/**", search: "" },
      { pathname: "/images/screenshots/**" },
    ],
  },

  // Performance optimizations for Core Web Vitals
  poweredByHeader: false, // Remove X-Powered-By header (security + performance)
  compress: true, // Enable Brotli/Gzip compression
  reactStrictMode: true, // Better development experience

  // Compiler optimizations for smaller bundles
  compiler: {
    // Remove console.log in production
    removeConsole: process.env.NODE_ENV === "production" ? { exclude: ["error", "warn"] } : false,
  },

  // Native modules that must not be bundled by Turbopack/webpack. `sharp` is
  // a prebuilt-binary module — bundling it can make the image-gen route slow
  // to compile in dev and breaks the runtime on some platforms. Externalising
  // it tells Next to `require()` it at runtime from node_modules instead.
  serverExternalPackages: ["sharp"],

  // Experimental features for performance
  experimental: {
    // `optimizeCss` runs `critters` over the global stylesheet to inline
    // critical CSS. With a 7k-line `globals.css` it pushes dev-server compile
    // times from "instant" to "many seconds per route", and Turbopack already
    // ships better CSS handling in dev. Scope to production where the LCP win
    // is worth the build-time cost.
    optimizeCss: process.env.NODE_ENV === "production",
    // Tree-shake icon barrels so a single `import { X } from "lucide-react"`
    // doesn't pull the whole icon catalog into the client bundle.
    optimizePackageImports: ["lucide-react", "framer-motion", "firebase"],
  },

  // Disable Vercel Toolbar in production
  devIndicators: false,

  // Allow ngrok dev origins (cross-origin HMR)
  allowedDevOrigins: ["*.ngrok-free.dev", "*.ngrok.io"],

  // Headers for security and caching
  async headers() {
    // Content Security Policy — defense-in-depth against XSS and data exfil.
    // 'unsafe-inline' on scripts is required for the theme-init script in
    // app/layout.tsx and JSON-LD blocks; migrating to nonce-based CSP would
    // require touching every Server Component. The other directives still
    // close the most exploitable attack surfaces (object embedding, base
    // hijacking, form-action redirection, framing).
    const csp = [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://*.firebaseio.com https://www.gstatic.com https://apis.google.com https://accounts.google.com",
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data: https://fonts.gstatic.com",
      "connect-src 'self' https: wss://*.firebaseio.com wss://*.firebase.com",
      "frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://accounts.google.com https://*.firebaseapp.com",
      "worker-src 'self' blob:",
      "media-src 'self' blob:",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self' https://checkout.stripe.com",
      "frame-ancestors 'none'",
      "upgrade-insecure-requests",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "Content-Security-Policy",
            value: csp,
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "X-Frame-Options",
            value: "DENY",
          },
          {
            key: "X-XSS-Protection",
            value: "1; mode=block",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(self), geolocation=()",
          },
          {
            // Isolate the browsing context from cross-origin pages while
            // still allowing OAuth popup flows (LinkedIn, Google) to work.
            key: "Cross-Origin-Opener-Policy",
            value: "same-origin-allow-popups",
          },
        ],
      },
      {
        // Cache static assets aggressively (images, fonts)
        source: "/(.*)\\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|avif|webp)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // Cache JS/CSS bundles
        source: "/_next/static/(.*)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // Service worker and manifest
        source: "/(sw.js|manifest.json)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=0, must-revalidate",
          },
        ],
      },
    ];
  },

  // Redirects for SEO (trailing slashes, www normalization)
  async redirects() {
    return [
      // Remove trailing slashes for consistency
      {
        source: "/:path+/",
        destination: "/:path+",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
