// Bluesky / AT Protocol helpers. No OAuth flow — auth is `handle + app
// password` (generated by the user in https://bsky.app/settings/app-passwords),
// exchanged for an accessJwt/refreshJwt pair via `com.atproto.server.createSession`.

export const BLUESKY_DEFAULT_SERVICE = "https://bsky.social";
// Max length of a Bluesky post in Unicode graphemes. The server actually
// counts graphemes but we approximate with codepoints — good enough for UI.
export const BLUESKY_MAX_POST_LENGTH = 300;

export interface BlueskySession {
  accessJwt: string;
  refreshJwt: string;
  handle: string;
  did: string;
}

export interface BlueskyProfile {
  did: string;
  handle: string;
  displayName?: string;
  avatar?: string;
}

export interface BlueskyPostResult {
  success: boolean;
  uri?: string;
  cid?: string;
  postUrl?: string;
  error?: string;
}

/**
 * Normalize a user-typed handle: strip leading "@", whitespace, lowercase, and
 * append ".bsky.social" if no domain was provided.
 */
export function normalizeHandle(raw: string): string {
  const trimmed = raw.trim().replace(/^@/, "").toLowerCase();
  if (!trimmed) return "";
  if (trimmed.includes(".")) return trimmed;
  return `${trimmed}.bsky.social`;
}

/**
 * Build the public URL for a post given the handle and AT URI rkey.
 */
export function buildPostUrl(handle: string, uri: string): string | undefined {
  // at://did:plc:xyz/app.bsky.feed.post/<rkey>
  const match = uri.match(/app\.bsky\.feed\.post\/([^/]+)$/);
  if (!match) return undefined;
  const rkey = match[1];
  return `https://bsky.app/profile/${handle}/post/${rkey}`;
}

/**
 * Create a Bluesky session. This is the equivalent of signing in.
 * identifier can be a handle ("alice.bsky.social"), a DID, or an email.
 */
export async function createBlueskySession(params: {
  identifier: string;
  password: string;
  service?: string;
}): Promise<BlueskySession> {
  const service = params.service || BLUESKY_DEFAULT_SERVICE;
  const response = await fetch(`${service}/xrpc/com.atproto.server.createSession`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      identifier: params.identifier,
      password: params.password,
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    let message = "Bluesky authentication failed";
    try {
      const json = JSON.parse(body);
      if (json?.message) message = json.message;
      else if (json?.error) message = json.error;
    } catch {
      // Non-JSON error body — fall back to generic message.
    }
    throw new Error(message);
  }

  const data = await response.json();
  return {
    accessJwt: data.accessJwt,
    refreshJwt: data.refreshJwt,
    handle: data.handle,
    did: data.did,
  };
}

/**
 * Refresh an expired access JWT using the refresh JWT.
 */
export async function refreshBlueskySession(params: {
  refreshJwt: string;
  service?: string;
}): Promise<BlueskySession> {
  const service = params.service || BLUESKY_DEFAULT_SERVICE;
  const response = await fetch(`${service}/xrpc/com.atproto.server.refreshSession`, {
    method: "POST",
    headers: { Authorization: `Bearer ${params.refreshJwt}` },
  });

  if (!response.ok) {
    throw new Error("Bluesky session refresh failed");
  }

  const data = await response.json();
  return {
    accessJwt: data.accessJwt,
    refreshJwt: data.refreshJwt,
    handle: data.handle,
    did: data.did,
  };
}

/**
 * Fetch the signed-in user's profile.
 */
export async function fetchBlueskyProfile(params: {
  accessJwt: string;
  handle: string;
  service?: string;
}): Promise<BlueskyProfile> {
  const service = params.service || BLUESKY_DEFAULT_SERVICE;
  const url = `${service}/xrpc/app.bsky.actor.getProfile?actor=${encodeURIComponent(params.handle)}`;
  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${params.accessJwt}` },
  });
  if (!response.ok) {
    throw new Error("Failed to fetch Bluesky profile");
  }
  const data = await response.json();
  return {
    did: data.did,
    handle: data.handle,
    displayName: data.displayName,
    avatar: data.avatar,
  };
}

/**
 * Publish a plain-text post to Bluesky.
 * Media upload + facet/link detection can be added later.
 */
export async function createBlueskyPost(params: {
  accessJwt: string;
  did: string;
  text: string;
  service?: string;
  handle?: string;
}): Promise<BlueskyPostResult> {
  const service = params.service || BLUESKY_DEFAULT_SERVICE;

  const record = {
    $type: "app.bsky.feed.post",
    text: params.text,
    createdAt: new Date().toISOString(),
    langs: [],
  };

  const response = await fetch(`${service}/xrpc/com.atproto.repo.createRecord`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${params.accessJwt}`,
    },
    body: JSON.stringify({
      repo: params.did,
      collection: "app.bsky.feed.post",
      record,
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    let message = "Bluesky post failed";
    try {
      const json = JSON.parse(body);
      if (json?.message) message = json.message;
      else if (json?.error) message = json.error;
    } catch {
      /* keep generic message */
    }
    return { success: false, error: message };
  }

  const data = await response.json();
  const postUrl = params.handle ? buildPostUrl(params.handle, data.uri) : undefined;

  return {
    success: true,
    uri: data.uri,
    cid: data.cid,
    postUrl,
  };
}
